---
title: "Dashboard Analise Iris"
author: "Ana Carolina Dias" 
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
    social: [ "twitter", "facebook", "linkedin" ]
    navbar:
      - { title: "Sobre Mim", href: "https://example.com/about", align: right }
      - { icon: fa-address-card, href: "https://example.com/about", align: right }
    logo: logo.png
    favicon: favicon.png
    #css: styles.css
---

```{r setup, include=FALSE}

# O include=FALSE serve para indicar que vamos rodar esse pedaço do codigo
# mas nem o código nem a saída são exibidos no arquivo.

library(readr)
library(ggplot2)
library(plotly)
library(flexdashboard)
library(DT)
library(tidyverse)

iris <- read_csv("iris.csv")

mean_values = iris %>% 
  summarise(media_SL = round(mean(sepal_length),3),
            media_SW = round(mean(sepal_width),3),
            media_PL = round(mean(petal_length),3),
            media_PW = round(mean(petal_width),3))


```

# Barra Lateral {.sidebar}

Esta barra lateral foi incluida somente 
na pagina de visualizações

```{r}

inputPanel(
selectInput("species", label = h3("Selecione a espécie:"), 
            
  choices = list("setosa",'versicolor','virginica','todas'), selected = "todas"))

```

# Visualizações {data-icon="fa-signal" data-navmenu="Analises"} 

## Column {data-width=500}

### Graficos de Pontos 

```{r}

renderPlotly({
  
grafico = ggplot(
  
  data = iris %>% 
         filter(str_detect(species, ifelse(input$species == 'todas',"",input$species))),
  
        aes(x=sepal_width, y=sepal_length, color = species)) + 
        geom_point()

ggplotly(grafico)

})



```

## Column {data-width=300}

### Boxplot 
```{r}

renderPlotly({
  
boxplot = ggplot(data = iris %>%  filter(str_detect(species, ifelse(input$species == 'todas',"",input$species))),
       aes(x=species, y=petal_length,color=species)) + 
  geom_boxplot() 

ggplotly(boxplot)

})

```

### Histograma

```{r}

renderPlotly({

histograma = ggplot(data =iris %>%  filter(str_detect(species, ifelse(input$species == 'todas',"",input$species))),
                    aes(x=sepal_length,fill=species)) + 
  geom_histogram() 

ggplotly(histograma)

})

```

# Tabelas {data-table=row data-icon="fa-list" data-navmenu="Analises"}

## Column {data-width=300}

### Tabela da base de Dados

```{r}


renderDataTable({
     DT::datatable(iris %>%  filter(str_detect(species, ifelse(input$species == 'todas',"",input$species))), options = list(lengthMenu = c(5, 10, 25), pageLength = 10))

})
```
